---

 - name: Add repository for Postgresql
  shell: "amazon-linux-extras install postgresql10"
- name: Install PostgreSQL
  yum: name={{ item }} update_cache=true state=latest
  with_items:
    - postgresql-server
    - postgresql-devel
    - git
    - docker
- name: Intialize DB
  shell: "/usr/bin/postgresql-setup --initdb"
  ignore_errors: yes

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Create the "database" user
  become: yes
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    encrypted: True
  become_user: postgres
- name: Ensure database is created
  become: yes 
  become_user: postgres
  postgresql_db: name={{ db_name }}
- name: Ensure user has access to the database
  become: yes
  postgresql_user: db={{ db_name }}
              name={{ db_user }}
              password={{ db_password }}
              priv=ALL
              state=present
- name: install docker 
  yum: 
      name: "{{ item }}"
      state: latest
  with_items:
        - docker
        - python2-pip
- name: Upgrade pip
  pip:
    name: docker 
    extra_args: --ignore-installed

- name: Install docker python module
  pip:
    name: docker 
- name: Start Docker service 
  service: 
      name: docker 
      state: started 
- name: Clone a Servian github repository
  git:
    repo: https://github.com/servian/TechChallengeApp.git
    dest: /home/app
    clone: yes
    update: yes
- name: Replace Db password 
  lineinfile:
      path: /home/app/conf.toml
      regexp: 'DbPassword'
      line: '"DbPassword" = "{{ db_password }}"'
      backrefs: yes
- name: Build container image with DockerFile
  docker_image:
      path: /home/app/
      name: myimage
- name: Create Conatiner 
  docker_container:
      name: techchallenge
      image: myimage:latest
      state: started
      command: updatedb && serve
      recreate: yes
